### ISSUE TITLE
Use of Assetic breaks Twital

### ISSUE THREAD

**Issue by petrmalina** [goetas/twital-bundle#3]
Use of the tag javascripts or stylesheets from the Assetic Bundle break the twital parser.
The t: syntax is not executed then.

Used packages:
symfony/assetic-bundle dev-master 4bfd74e
symfony/symfony v2.6.7
twig/twig v1.18.1
goetas/twital 0.1.6
goetas/twital-bundle 0.1.1

**Comment by goetas** [comment]
Hi! Can you post part of the template that breaks the parser?

**Comment by petrmalina** [comment]
Hi goetas, thanks for your reply.

The code is not executed whenever you use Assetic.

Example:
```twig
{% block stylesheets %}
    {{ parent() }}
    {% stylesheets  'bundles/frontend/less/basket.less' filter='cssrewrite' %}
    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts  'bundles/frontend/js/basket.js' filter='jsqueeze' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}
```

Any following Twital directives are not evaluated then.

**Comment by petrmalina** [comment]
Hi goteas, any updates?

**Comment by goetas** [comment]
Hi https://github.com/goetas/twital/commit/73914d74a1161431b0686c140e7b28ad006ebc4f should fix your issue. Can you let me know if is working?

You have to install the master dev version of twital to test it. This means: 

```json
    "require" : {
        "goetas/twital-bundle": "*",
        "goetas/twital" : "~0.1@dev"
    }
```

**Comment by goetas** [comment]
Suppose issue is fixed
