### ISSUE TITLE
Release Symfony 3.x support

### ISSUE THREAD

**Issue by msgilligan** [goetas/twital-bundle#6]
I see Symfony 3.0 support on the `master` branch, but no release yet. Is there a release coming soon?

**Comment by goetas** [comment]
Starting from https://github.com/goetas/twital-bundle/tree/0.1.2 (v0.1.2) yes, sf3 is supported

**Comment by msgilligan** [comment]
Can you update the documentation to reflect this? How do you download and install it?

I'm a front-end developer on a project and I had suggested my client look at Twital for a template library. So I can only point them at the documentation and ask that they try this out...

**Comment by msgilligan** [comment]
Just go word from my client, we're going to use Symfony 2 -- not clear yet which template library we're going to use. 

I still recommend you update your documentation, though. :)

**Comment by msgilligan** [comment]
We are up and running on Symfony 2.8, by the way - Thanks!

**Comment by goetas** [comment]
Glad to hear
